apiVersion: apps/v1
kind: Deployment
metadata:
  name: banana-front
  labels:
    app: banana-front
  namespace: banana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: banana-front
  template:
    metadata:
      labels:
        app: banana-front
    spec:
      containers:
        - name: banana-front
          image: rg.fr-par.scw.cloud/banana-front/banana-front:9175923d6c116cef13b5dd7819d0322bc837eee4
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: banana-front
  labels:
    app: banana-front
spec:
  type: ClusterIP
  selector:
    app: banana-front
  ports:
    - port: 80
      targetPort: 80